### ISSUE TITLE
Ability to view other branches/tags for Go standard library.

### ISSUE THREAD

**Issue by foolusion** [shurcooL/gtdo#45]
Hi I'm wondering if there is a way to target certain branches or view tip of std lib packages.

**Comment by shurcooL** [comment]
There isn't a way right now, but this is something I'd really like to add.

**Comment by shurcooL** [comment]
This task is resolved now via #49, and it's possible to view any part of Go standard library (including `cmd` subdirectory with command) at any revision, branch, tag, and even CL.

For example:

- https://gotools.org/time - `time` package in stable Go release (1.8.3 at this time)
- https://gotools.org/time?rev=master - `time` package on master branch (aka tip)
- https://gotools.org/time?rev=go1.9rc2 - `time` package in Go 1.9 RC 2
- https://gotools.org/bytes?rev=refs/changes/16/42816/4 - `bytes` package in [CL 42816](https://golang.org/cl/42816)
- https://gotools.org/pkg/net/http?rev=go1 - `net/http` package in Go 1 ("pkg" prefix is needed because back then, GOROOT packages were in GOROOT/src/pkg instead of GOROOT/src)

To view a CL, just use its revision. It's the same process as [checking out that CL locally](https://golang.org/doc/contribute.html#download). You visit the CL page, press Download link and copy the revision from there:

![image](https://user-images.githubusercontent.com/1924134/29386732-1afeaa0c-82ab-11e7-9650-4888e313161b.png)
![image](https://user-images.githubusercontent.com/1924134/29386749-32f1d508-82ab-11e7-997d-6b50988a9792.png)
