### ISSUE TITLE
Improvement of design

### ISSUE THREAD

**Issue by ShoshinNikita** [shurcooL/gtdo#54]
I guess, the menu for quick access to files (div with id `#toc-results`) would look better with `style` attribute.

For example, even with such code `style="width: 150px; overflow-x: hidden; overflow-y: auto; padding: 3px; background-color: white;"` the menu starts to look better.

Before
![before](https://user-images.githubusercontent.com/30220965/40589219-346afac8-61f2-11e8-920b-684be7a1a2d8.png)

After
![after](https://user-images.githubusercontent.com/30220965/40589262-b4827056-61f2-11e8-96fd-18e9e0a3bca9.png)

**Comment by shurcooL** [comment]
That looks like a bug, there shouldn't be disabled scrollbars visible. This is what it should look like:

![image](https://user-images.githubusercontent.com/1924134/40638358-ecb0589e-62d8-11e8-8383-4908d648434f.png)

That's what I get on latest stable Chrome and in Safari on macOS 10.13.4.

What browser and OS are you using?

**Comment by ShoshinNikita** [comment]
I changed `overflow: scroll;` to `overflow: auto;`. It solved the bug.

![screenshot_1](https://user-images.githubusercontent.com/30220965/40641559-ca3fad2e-6322-11e8-81c6-a156f939def3.png)
![screenshot_2](https://user-images.githubusercontent.com/30220965/40641560-ca62671a-6322-11e8-82ab-6ef19e79a52f.png)

**Comment by shurcooL** [comment]
> OS: Windows 10
> Browser: main browser is Yandex Browser.
>
> But I checked other browsers. There's the same bug.

Thanks. I can reproduce it now too.

It turns out it wasn't related so much to browser/OS type, but rather to the way setting controlling whether the scrollbars are displayed. I can reproduce it in Chrome and Safari on macOS if I set the scrollbars to always show up (normally, I have them set to only be visible during scrolling, which doesn't create extra width):

![image](https://user-images.githubusercontent.com/1924134/40795235-64eadd5a-64cf-11e8-8fe9-f54d3b1dc1ba.png)

> I changed `overflow: scroll;` to `overflow: auto;`. It solved the bug.

This is a good start, but it's not going to work well in all situations. It's important we consider both the case where the Table of Contents is short and a vertical scrollbar isn't needed, and the case where it's long and a vertical scrollbar is needed. If we just use `overflow: auto;`, it works okay for the short case, but not the long case:

![image](https://user-images.githubusercontent.com/1924134/40795367-dc005316-64cf-11e8-8d89-f69698c1809f.png)

We don't want the horizontal scrollbar to ever appear, because most filenames are short enough to fit. So we can do:

```CSS
overflow-y: auto;
overflow-x: hidden;
```

When `overflow-x: hidden;` is set, `overflow-y: auto;` seems to behave the same as `overflow-y: visible;`, which is the default setting. So we can simplify the CSS to just `overflow-x: hidden;`. It seems to work well in all browsers I tried:

![image](https://user-images.githubusercontent.com/1924134/40795535-5bb66406-64d0-11e8-9a82-469501afda22.png)

When the TOC is short, there are no scrollbars:

![image](https://user-images.githubusercontent.com/1924134/40795555-690a928a-64d0-11e8-9b31-ae6886b75fb7.png)

**Comment by ShoshinNikita** [comment]
Good. But maybe it would be better to increase width (maybe ```width: auto;```)?
For example, names of files can't fit here.

> ![1](https://user-images.githubusercontent.com/1924134/40795535-5bb66406-64d0-11e8-9a82-469501afda22.png)

Although, I noticed everything is okay on my PC. It's interesting.

![screenshot_1](https://user-images.githubusercontent.com/30220965/40796044-77086ce0-650c-11e8-8eb2-50b30de5eaf8.png)

**Comment by ShoshinNikita** [comment]
And what about adding ```padding```? I guess it looks more clear, and it's easier to read the names of files.

**Comment by shurcooL** [comment]
> Although, I noticed everything is okay on my PC.

I'm guessing you used Chrome in that screenshot, right? Chrome seems to display things differently (the scrollbar doesn't cover up the content).

I tried `width: auto;`, it doesn't seem to help (in Safari).

> And what about adding `padding`? I guess it looks more clear, and it's easier to read the names of files.

I'll think about it, but it seems like a very marginal improvement, not worth spending time on.

**Comment by ShoshinNikita** [comment]
Ok. Thank you for the quick answer!
