### ISSUE TITLE
error loading page

### ISSUE THREAD

**Issue by foolusion** [shurcooL/gtdo#55]
tried to get https://gotools.org/k8s.io/kubernetes/pkg/controller/replicaset and got the following error 

2 errors:
branch not found
exec `git remote update` failed: exit status 1. Stderr was:

fatal: git fetch-pack: expected ACK/NAK, got 'ERR upload-pack: not our ref fda030a8684caa391a52d9984d87efbb62cc2415'
fatal: The remote end hung up unexpectedly
error: Could not fetch origin

**Comment by dmitshur** [comment]
Hi, thanks for the report.

Kubernetes is a very large repository, and the problem is that gotools.org is running on a very small server right now. So it often has trouble when trying to display a package in a large repo.

The error message you posted sounds like it failed to update the repo, perhaps also due to a temporary network issue.

It seems to be working now, although slowly, so there's nothing specific to do here.

I plan to overhaul gotools.org with a new module-aware version, which should help with performance of displaying Go packages in large repos.
